---

name: tox
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.tox_env }}
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: lint
            python-version: "3.9"
          - tox_env: packaging
            python-version: "3.9"
            # - tox_env: py38
            #   PREFIX: PYTEST_REQPASS=2
            #   python-version: "3.8"
            # - tox_env: py39
            #   PREFIX: PYTEST_REQPASS=2
            #   python-version: "3.9"
            # - tox_env: py310
            #   PREFIX: PYTEST_REQPASS=2
            #   python-version: "3.10"
            # - tox_env: py38-devel
            #   PREFIX: PYTEST_REQPASS=2
            #   python-version: "3.8"
            # - tox_env: py310-devel
            #   PREFIX: PYTEST_REQPASS=2
            #   python-version: "3.10"

    steps:
      - uses: actions/checkout@v3

      # - name: LXD init
      #   uses: https://github.com/canonical/setup-lxd@v0.1.1

      - name: Enable caching of ~/.cache/pip
        uses: https://github.com/actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.python-version }}-${{ hashFiles('**/setup.cfg', 'tox.ini') }}

      # Be sure to install the version of python needed by a specific test, if necessary
      # - name: Set up Python version
      #   uses: https://github.com/actions/setup-python@v4
      #   with:
      #     python-version: '${{ matrix.python-version }}'
      #     cache: 'pip'

      - name: Install python3
        run: apt-get update && apt-get install python3-pip python3-venv -y

      - name: Install tox
        run: python3 -m pip install tox

      - name: Run tox -e ${{ matrix.tox_env }}
        run: ${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}
